<a href="https://colab.research.google.com/github/AnIsAsPe/Aprendizaje-por-Refuerzo/blob/main/Introducci%C3%B3n_a_OpenIA_Gym.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Instalación de dependencias y creación de display

[Referencia](https://davidrpugh.github.io/stochastic-expatriate-descent/openai/binder/google-colab/2020/04/16/remote-rendering-gym-envs.html)


In [8]:
# instalar dependencias del sistema
!apt-get install -y xvfb x11-utils

# instalar requerimientos de dependencias de Python
!pip install gym[box2d]==0.17.* pyvirtualdisplay==0.2.* PyOpenGL==3.1.* PyOpenGL-accelerate==3.1.*

Reading package lists...
Building dependency tree...
Reading state information...
x11-utils is already the newest version (7.7+3build1).
xvfb is already the newest version (2:1.19.6-1ubuntu4.8).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.


In [1]:
#para comprobar que aun no hay variable del entorno
!echo $DISPLAY

In [2]:
#iniciar display
import pyvirtualdisplay


_display = pyvirtualdisplay.Display(visible=False, size=(1400, 900))
_ = _display.start()

In [3]:

!echo $DISPLAY

:1013


 # Ejercicio con GYM

In [23]:
import gym
import numpy as np
import matplotlib.pyplot as plt

La librería Gym busca proveer de una basta colección de ambientes. 

Podemos consultar los ambientes disponibles con el comando `gym.envs.registry`



In [5]:
gym.envs.registry.all()

dict_values([EnvSpec(Copy-v0), EnvSpec(RepeatCopy-v0), EnvSpec(ReversedAddition-v0), EnvSpec(ReversedAddition3-v0), EnvSpec(DuplicatedInput-v0), EnvSpec(Reverse-v0), EnvSpec(CartPole-v0), EnvSpec(CartPole-v1), EnvSpec(MountainCar-v0), EnvSpec(MountainCarContinuous-v0), EnvSpec(Pendulum-v0), EnvSpec(Acrobot-v1), EnvSpec(LunarLander-v2), EnvSpec(LunarLanderContinuous-v2), EnvSpec(BipedalWalker-v3), EnvSpec(BipedalWalkerHardcore-v3), EnvSpec(CarRacing-v0), EnvSpec(Blackjack-v0), EnvSpec(KellyCoinflip-v0), EnvSpec(KellyCoinflipGeneralized-v0), EnvSpec(FrozenLake-v0), EnvSpec(FrozenLake8x8-v0), EnvSpec(CliffWalking-v0), EnvSpec(NChain-v0), EnvSpec(Roulette-v0), EnvSpec(Taxi-v3), EnvSpec(GuessingGame-v0), EnvSpec(HotterColder-v0), EnvSpec(Reacher-v2), EnvSpec(Pusher-v2), EnvSpec(Thrower-v2), EnvSpec(Striker-v2), EnvSpec(InvertedPendulum-v2), EnvSpec(InvertedDoublePendulum-v2), EnvSpec(HalfCheetah-v2), EnvSpec(HalfCheetah-v3), EnvSpec(Hopper-v2), EnvSpec(Hopper-v3), EnvSpec(Swimmer-v2), EnvSp

EnvSpec es el tipo de objeto de estos ambientes. Cada uno de ellos incluye los parametros para ejecutar cierta tarea.

Los podemos usar simplemente usando `gym.make()`

In [6]:
carro = gym.make('MountainCar-v0')  #crear ambiente
             


En este ambiente, un estado es definido por la posición horizontal del coche y la velocidad.


In [7]:
#estados
carro.observation_space  # posición y velocidad

Box(-1.2000000476837158, 0.6000000238418579, (2,), float32)

In [17]:
carro.observation_space.low

array([-1.2 , -0.07], dtype=float32)

In [18]:
carro.observation_space.high

array([0.6 , 0.07], dtype=float32)

In [9]:
#acciones
carro.action_space.n  

3

Tres acciones correpondientes a:
* (0) acelerar a la izquierda, 
* (1) acelerar a la derecha, 
* (2) no acelerar.

In [19]:
carro.reset()

array([-0.46195147,  0.        ])

In [21]:
a = 2  #acción 2
carro.step(1)


(array([-4.61334626e-01,  7.65704749e-05]), -1.0, False, {})

In [10]:
carro.action_space.sample()  # genera una acción aleatoria con distribución uniforme, sin considerar el espacio actual

0

In [16]:
carro = gym.make('MountainCar-v0')  #crear ambiente
carro.reset()                       #reiniciar ambiente               

for t in range(5):
        carro.render()                          #para ver lo que está pasando en cada accion
        accion = carro.action_space.sample()
        estado, ganancia, logro, info = carro.step(accion)
        print("\nTiempo: ", t+1)
        print("accion: ",accion)
        print("estado: ", estado)        # tiempo y velocidad
        print("ganancia: ", ganancia)                #la ganancia de la última acción
        print("logro: ", logro)                      #informa cuando se ha alcanzado el objetivo
        print("info: ", info)                      #es útil cuando algo va mal

        if done:
            print("Se alcanzó la menta en  {} tiempos".format(t+1))
            break
carro.close()


Tiempo:  1
accion:  0
estado:  [-0.5574997  -0.00075179]
ganancia:  -1.0
logro:  False
info:  {}
Se alcanzó la menta en  1 tiempos


In [13]:
carro = gym.make('MountainCar-v0')  #crear ambiente
carro.reset()                       #reiniciar ambiente               

for t in range(1000):
        carro.render()                          #para ver lo que está pasando en cada accion
        accion = carro.action_space.sample()
        estado, ganancia, done, info = carro.step(accion)

        if done:
            print("Se alcanzó la meta en  {} tiempos".format(t+1))
            print("estado: ", estado)        
            print("ganancia: ", ganancia)             
            print("done: ", done)                     
            print("info: ", info)                     
            break
carro.close()

Se alcanzó la menta en  200 tiempos
observation:  [-0.57444622 -0.00326375]
reward:  -1.0
done:  True
info:  {'TimeLimit.truncated': True}


# Referencias

1. Peterson H. Demystifying Markov Decision Processes [Internet]. Medium. 2020 [citado 23 de febrero de 2021]. Disponible en: https://medium.com/gsi-technology/demystifying-markov-decision-processes-cd8f119aa3d1
2. Sonawane B. Getting started with OpenAI Gym [Internet]. Medium. 2020 [citado 23 de febrero de 2021]. Disponible en: https://towardsdatascience.com/getting-started-with-openai-gym-d2ac911f5cbc
3. OpenAI. Gym: A toolkit for developing and comparing reinforcement learning algorithms [Internet]. [citado 23 de febrero de 2021]. Disponible en: https://gym.openai.com
4. RANA A. Introduction: Reinforcement Learning with OpenAI Gym [Internet]. Medium. 2019 [citado 23 de febrero de 2021]. Disponible en: https://towardsdatascience.com/reinforcement-learning-with-openai-d445c2c687d2
5. Pugh DR, Pugh DR. Rendering OpenAI Gym Envs on Binder and Google Colab [Internet]. Stochastic Expatriate Descent. 2020 [citado 23 de febrero de 2021]. Disponible en: https://davidrpugh.github.io/stochastic-expatriate-descent/openai/binder/google-colab/2020/04/16/remote-rendering-gym-envs.html
1. Hayes G. Getting Started with Reinforcement Learning and Open AI Gym [Internet]. Medium. 2019 [citado 23 de febrero de 2021]. Disponible en: https://towardsdatascience.com/getting-started-with-reinforcement-learning-and-open-ai-gym-c289aca874f

